### ISSUE TITLE
头像和文字是如何合称为一张图片的？

### ISSUE THREAD

**Issue by zemise** [xslingcn/Phenyl#8]
已找到对应代码，谢谢大佬了！

**Comment by abc408880155** [comment]
我也使用了Mirari，但目前只能做到简单的输出头像图片和文字，没找到合适的方式做到像您一样
<img width="438" alt="image" src="https://user-images.githubusercontent.com/46216418/200097913-db9850af-cd2e-4243-87ce-d6f7f93d1452.png">

**Comment by xslingcn** [comment]
For any future reference : )[https://github.com/xslingcn/Phenyl/blob/6acff06f6c699edab82c5cf79c55a74f153bcdbd/common/src/main/java/live/turna/phenyl/common/message/ImageMessage.java#L41](https://github.com/xslingcn/Phenyl/blob/6acff06f6c699edab82c5cf79c55a74f153bcdbd/common/src/main/java/live/turna/phenyl/common/message/ImageMessage.java#L41)
